apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: api.apps.tanzu.vmware.com
spec:
  group: tanzu.vmware.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string

  scope: Namespaced
  names:
    plural: apidescriptors
    singular: apidescriptor
    kind: APIDescriptor