apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: crd-delivery
spec:
  selector:
    app.tanzu.vmware.com/deliverable-type: web
    app.tanzu.vmware.com/register-api: "true"

  resources:
    - name: source-provider
      templateRef:
        kind: ClusterSourceTemplate
        name: delivery-source-template
      params:
        - name: serviceAccount
          value: default
        - name: gitImplementation
          value: go-git

    - name: deployer
      templateRef:
        kind: ClusterDeploymentTemplate
        name: app-deploy
      params:
        - name: serviceAccount
          value: default
      deployment:
        resource: source-provider
