---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: petclinic-api-entity-foo
  namespace: my-apps
  description: The Spotify web API
  tags:
    - spotify
    - rest
spec:
  type: openapi
  lifecycle: experimental # how can we infer lifecycle
  owner: team-a
  definition:
    '$text': 'http://petclinic-api-entity.my-apps.api-entity-registration-demo.tapdemo.vmware.com/v3/api-docs'
