apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: petclinic-api-entity
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.kubernetes.io/name: spring-petclinic
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: spring-petclinic
    app.tanzu.vmware.com/register-api: "true"
spec:
  source:
    git:
      url: https://github.com/sample-accelerators/spring-petclinic.git
      ref:
        branch: main
        tag: tap-1.1
