apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: petclinic-api-entity
  namespace: my-apps
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.kubernetes.io/name: spring-petclinic
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: spring-petclinic
    app.tanzu.vmware.com/register-api: "true"
  annotations:
    openapi-spec-endpoint: "/v3/api-docs"
    server-url: "topangas"
spec:
  source:
    git:
      url: https://github.com/LittleBaiBai/spring-petclinic.git
      ref:
        branch: accelerator
